### ISSUE TITLE
crashed on startup!)

### ISSUE THREAD

**Issue by zc1108aaa** [brunohpaiva/better-sign-edit#4]
[latest.log](https://github.com/brunohpaiva/better-sign-edit/files/15257711/latest.log)
[crash-2024-05-09_12.52.16-client.txt](https://github.com/brunohpaiva/better-sign-edit/files/15257712/crash-2024-05-09_12.52.16-client.txt)

**Comment by brunohpaiva** [comment]
Hey, sorry for the delay.

Fixed in version 1.1.1 for MC 1.20.5 and up.
Modrinth: https://modrinth.com/mod/better-sign-edit/version/1.1.1-mc1.20.5
Also in CurseForge but it's still in review.
